apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: app
  labels:
    app: petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic